name: OpenAI Code Review

on:
  pull_request:
    branches:
      - '*'

jobs:
  code_review_job:
    name: OpenAI Code Review
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11' # Specify the version of Java you are using
          distribution: 'adopt'
          
      - name: Run OpenAI Code Review
        uses: cirolini/genai-code-review@v2
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_pr_id: ${{ github.event.number }}
          openai_model: "gpt-3.5-turbo" # Specify the OpenAI model to use
          mode: files # Review entire files
          language: java # Specify the language of the code to be reviewed
