name: OpenAI code review

on:
  pull_request:
    branches:
      - "*"
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  openai-code-review:
    runs-on: ubuntu-latest
    name: OpenAI code review
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: OpenAI code review
        uses: anc95/ChatGPT-CodeReview@v1.0.13
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          # Optional configuration
          LANGUAGE: English
          files: "*.java"
          MODEL: gpt-3.5-turbo
          PROMPT: "Please review the following code changes:"
          top_p: 1
          temperature: 1
          max_tokens: 10000
          MAX_PATCH_LENGTH: 10000
